//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginUDEO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bodegaProducto
    {
        public int idProducto { get; set; }
        public int idBodega { get; set; }
        public int cantidad { get; set; }
        public int estado { get; set; }
    
        public virtual Bodega Bodega { get; set; }
        public virtual estado estado1 { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
