//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginUDEO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bodega
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bodega()
        {
            this.bodegaProducto = new HashSet<bodegaProducto>();
        }
    
        public int idBodega { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> telefono { get; set; }
        public Nullable<int> fax { get; set; }
    
        public virtual estado estado1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bodegaProducto> bodegaProducto { get; set; }
    }
}
